### ISSUE TITLE
Support vhosts without leading / ?

### ISSUE THREAD

**Issue by sgulseth** [rexxars/gleipnir#2]
If you pass the connection string `host:port/vhost` gleipnir currently parses this and uses the vhost `/vhost`, is this intentionally? amqplib uses `%2F` to support slashes in vhosts. 

http://www.squaremobius.net/amqp.node/channel_api.html#connect
> a trailing slash as in 'amqp://localhost/' would indicate the virtual host with an empty name, which does not exist unless it's been explicitly created. When specifying another virtual host, remember that its name must be escaped; so e.g., the virtual host named /foo is '%2Ffoo'; in a full URI, 'amqp://localhost/%2Ffoo'.

**Comment by rexxars** [comment]
Not intentional - feel like contributing with a PR? :)

**Comment by sgulseth** [comment]
Will do, wasn't sure if it was the lib that was opinionated against it or not :)
